server:
  # 端口
  port: 8087

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://MGXY-migudmzftp004:8001/eureka/,http://MGXY-migudmzftp005:8001/eureka/
    healthcheck:
        enabled: true
        instance:
            lease-expiration-duration-in-seconds: 30
            lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: hugetable-sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    name: macaw-ht-ds
    driver-class-name: com.chinamobile.cmss.ht.Driver
    url: jdbc:ha://192.168.129.187,192.168.129.186/hbase_test
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: true
      # 连接池最大使用连接数
      max-active: 64
      # 初始化连接大小
      initial-size: 4
      # 获取连接最大等待时间
      max-wait: 60000
      # 连接池最小空闲
      min-idle: 3
      # 自动清除无用连接
      remove-abandoned: true
      # 清除无用连接的等待时间
      remove-abandoned-timeout: 180
      # 连接属性
      connection-properties: clientEncoding=UTF-8
  redis:
      # Redis数据库索引（默认为0）
      database: 4
      # Redis服务器地址
      host: 172.18.111.9
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
  jackson:
    default-property-inclusion: NON_NULL


# 日志
logging:
  level:
    cn.migu: INFO

