server:
  # 端口
  port: 8085

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://MGXY-migudmzftp004:8001/eureka/,http://MGXY-migudmzftp005:8001/eureka/
    healthcheck:
        enabled: true
        instance:
            lease-expiration-duration-in-seconds: 30
            lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: jar-boot
  datasource:
    name: macaw-jarboot-ds
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.111.8:3306/bigdata_platform?useSSL=false&characterEncoding=UTF-8
    username: service
    password: Emc20090
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池最大使用连接数
      max-active: 200
      # 初始化连接大小
      initial-size: 1
      # 获取连接最大等待时间
      max-wait: 60000
      # 连接池最小空闲
      min-idle: 3
      # 自动清除无用连接
      remove-abandoned: true
      # 清除无用连接的等待时间
      remove-abandoned-timeout: 180
      # 连接属性
      connection-properties: clientEncoding=UTF-8
  jackson:
    default-property-inclusion: NON_NULL


# mybatis配置
mybatis:
  type-aliases-package: cn.migu.macaw.jarboot.api.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    database-id: bigdata_platform
    # 开启字段名和属性名驼峰匹配
    map-underscore-to-camel-case: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    aggressive-lazy-loading: true

mapper:
  mappers: cn.migu.macaw.common.mapper.CommonMapper
  not-empty: false
  identity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spark:
  master-url: spark://192.168.129.186:7077
hdfs:
  schema-prefix: hdfs://hadoop
macaw:
  custom-etl-jar-name: migu-ext-etl.jar
  custom-etl-jar-path: /apps/service/dst
  custom-etl-class-name: cn.migu.ext.etl.DataHandle4JF
  custom-etl-jar-main: cn.migu.file.core.Mapp
  zookeeper-url: 172.18.111.4:2182,172.18.111.5:2182,172.18.111.6:2182
  data-collect-roll-interval: 10
  sql-query-url: http://x.x.x.x:y/jar-boot/sql-query
  sql-execute-url: http://x.x.x.x:y/jar-boot/sql-execute
  batch-sql-execute-url:  http://x.x.x.x:y/jar-boot/sql-batchUpdate
  process-add: http://x.x.x.x:y/jar-boot/insertProcess
  data-file-log-update: http://x.x.x.x:y/jar-boot/updateDataFileLog
  hdfs-log-add: http://x.x.x.x:y/jar-boot/addHdfsLogTmp


# 日志
logging:
  level:
    cn.migu: INFO

